name: deploy-auth

on:
  push:
    branches:
      - main
    paths:
      - 'auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: DOCKER
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t leonardoramosc/ticketing-auth .
      - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - run: docker push leonardoramosc/ticketing-auth
